name: Generate Daily Article

on:
  schedule:
    - cron: '30 23 * * *'   # UTC 23:30 -> 台灣 07:30
    - cron: '30 7 * * *'    # UTC 07:30 -> 台灣 15:30
    - cron: '30 14 * * *'   # UTC 14:30 -> 台灣 22:30
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate article
        run: node .github/scripts/generate.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ARTICLE_PROMPT: ${{ secrets.ARTICLE_PROMPT }}

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add .
          git commit -m "chore: add new article $(date +'%Y-%m-%d %H:%M')" || echo "No changes"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
